package Modelos;

public record ConversionList(Double USD, Double ARS, Double BOB, Double BRL, Double CLP, Double COP) {
}

//public record ConversionList(double USD, double AED, double AFN, double ALL, double AMD, double ANG, double AOA, double ARS, double AUD, double AWG, double AZN, double BAM, double BBD, double BDT, double BGN, double BHD, double BIF, double BMD, double BND, double BOB, double BRL, double BSD, double BTN, double BWP, double BYN, double BZD, double CAD, double CDF, double CHF, double CLP, double CNY, double COP, double CRC, double CUP, double CVE, double CZK, double DJF, double DKK, double DOP, double DZD, double EGP, double ERN, double ETB, double EUR, double FJD, double FKP, double FOK, double GBP, double GEL, double GGP, double GHS, double GIP, double GMD, double GNF, double GTQ, double GYD, double HKD, double HNL, double HRK, double HTG, double HUF, double IDR, double ILS, double IMP, double INR, double IQD, double IRR, double ISK, double JEP, double JMD, double JOD, double JPY, double KES, double KGS, double KHR, double KID, double KMF, double KRW, double KWD, double KYD, double KZT, double LAK, double LBP, double LKR, double LRD, double LSL, double LYD, double MAD, double MDL, double MGA, double MKD, double MMK, double MNT, double MOP, double MRU, double MUR, double MVR, double MWK, double MXN, double MYR, double MZN, double NAD, double NGN, double NIO, double NOK, double NPR, double NZD, double OMR, double PAB, double PEN, double PGK, double PHP, double PKR, double PLN, double PYG, double QAR, double RON, double RSD, double RUB, double RWF, double SAR, double SBD, double SCR, double SDG, double SEK, double SGD, double SHP, double SLE, double SLL, double SOS, double SRD, double SSP, double STN, double SYP, double SZL, double THB, double TJS, double TMT, double TND, double TOP, double TRY, double TTD, double TVD, double TWD, double TZS, double UAH, double UGX, double UYU, double UZS, double VES, double VND, double VUV, double WST, double XAF, double XCD, double XDR, double XOF, double XPF, double YER, double ZAR, double ZMW, double ZWL) {
//}
//C:\Users\JuanF\IdeaProjects\Exchange\src\Modelos\ConversionList.java:3:8
//java: too many parameters
//Mensaje al usar los 162 atributos
//La dejaremos sólo con las 6 sugeridas